apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: claim-finalizer-service-api
  description: "The Claim Finalizer Service performs the finalization steps necessary during claim processing for a Veteran's application."
spec:
  type: openapi
  lifecycle: production
  owner: "claims"
  definition:
    $text: https://github.com/dstrivelli/claim-finalizer-service/blob/master/openapi.yaml
